name: Deploy to Azure Static Web Apps

on: [ release ]

env:
  NODE_VERSION: "15.x"
  AZURE_WEBAPP_NAME: "adminmt"
  NEXT_PUBLIC_API_URL: "https://api-gpmt.westeurope.cloudapp.azure.com"

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-

      - name: npm install
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install
      
      - name: Run jest unittest
        run: npm run test:unit
    
    
  deployment:
    runs-on: ubuntu-latest
    name: Deployment to Azure

    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - run: |
          docker build . -t ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/gpmt-admin:${{ github.event.release.tag_name }}
          docker push ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/gpmt-admin:${{ github.event.release.tag_name }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/gpmt-admin:${{ github.event.release.tag_name }}
      
      - name: logout
        run: az logout
